name: firstproject_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  animate_do: ^4.2.0
  fl_chart: ^0.70.2
  provider: ^6.1.2
  geolocator: ^13.0.3
  flutter_dotenv: ^5.0.2
  flutter_spinkit: ^5.1.0
  package_info_plus: ^4.0.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
